stages:
  - build
#  
# to avoid downloading the same content several times. Once a job is completed,
# the listed paths will be archived, and next job will use the same archive.
cache:
  paths:
    - /apt-cache
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in

build:
  stage: build
  image: golang:1.9.2

  before_script:
    # Create a symbolic link under $GOPATH, this is needed for local build
    # i.e. /go/src/gitlab.com/ykyuen/gitlab-ci-go-build
    - cd $GOPATH/src
    - mkdir -p gitlab.com/$CI_PROJECT_NAMESPACE/$CI_NAME
    - cd gitlab.com/$CI_PROJECT_NAMESPACE/$CI_NAME
    - ln -s $CI_PROJECT_DIR
    - cd $CI_NAME


script:
    -  go get -v -t -d ./account-api/...
    -  go build -v ./account-api/cmd
    -  go get -v -t -d ./marketing-api/...
    -  go build -v ./marketing-api/cmd
    -  go get -v -t -d ./auth-api/...
    -  go build -v ./auth-api/cmd
